services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: uiop00
      DB_NAME: ferreteria
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: uiop00
      MYSQL_DATABASE: ferreteria
    volumes:
      - /mnt/mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always

